#!/bin/bash

SCRIPT_NAME="XMonad Install"
SCRIPT_VERSION="1.0"
HELP_MESSAGE="\n%s %s, an xmonad wm installer\nUsage: xmonad-install [Options]... [Place Holder]\n\nOptions:\n -V, --version\t\tDisplay script version.\n -h, --help\t\tShow this help message.\n\n"
VERSION_MESSAGE="%s version %s\n"

OPTION_NOT_RECOGNIZED_MESSAGE="Option %s not recognized\n"

KEYMAP="latam"

LIGHTDM_XSESSION_FILE_PATH="/etc/lightdm/Xsession"

function installXorg() {
	pacman -S xorg xorg-xinit
}

function installXmonad() {
	pacman -S xmonad xmonad-contrib xmobar
}

function installPulseAudio() {
	pacman -S pulseaudio pavucontrol
	pulseaudio --check
	pulseaudio -D
}

function setKeymap() {
	printf "\n# Set xkb map - generated by xmonad-install.sh\n" >> "$LIGHTDM_XSESSION_FILE_PATH"
	printf "setxkbmap $KEYMAP" >> "$LIGHTDM_XSESSION_FILE_PATH"
}

function main() {
	installXorg
	installXmonad
	installPulseAudio
	setKeymap
}

while [[ "$1" =~ ^- ]]; do
	case "$1" in

		-h | --help) printf "$HELP_MESSAGE" "$SCRIPT_NAME" "$SCRIPT_VERSION" & exit ;;

		-V | --version) printf "$VERSION_MESSAGE" "$SCRIPT_NAME" "$SCRIPT_VERSION" & exit ;;

		-*) printf "$OPTION_NOT_RECOGNIZED_MESSAGE" "$file_path" & exit ;;

	esac

	shift
done

main